# Generated by Django 4.0.7 on 2026-02-03 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('ownership_type', models.CharField(max_length=50)),
                ('estd_year', models.IntegerField(default=2000)),
                ('cutoff_rank', models.IntegerField(default=5000, help_text='Closing rank for General category')),
                ('nirf_rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('college_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('eligible_category', models.CharField(help_text='e.g. SC, ST, OBC, All', max_length=50)),
                ('max_income', models.IntegerField(help_text='Maximum annual family income in INR')),
                ('state', models.CharField(help_text="Domicile State or 'All'", max_length=100)),
                ('amount', models.CharField(help_text='e.g. ₹30,000/year or Full Fee', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_fees', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('eligibility', models.CharField(default='10+2 with 50% marks', max_length=255)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='colleges.college')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni_audited_count', models.IntegerField(default=0)),
                ('open_to_work_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_tenure_months', models.DecimalField(decimal_places=1, max_digits=4)),
                ('top_employers', models.JSONField(default=list)),
                ('risk_score', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='colleges.college')),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course_name', models.CharField(help_text='e.g. B.Tech CS', max_length=100)),
                ('passout_year', models.IntegerField()),
                ('hometown_city', models.CharField(db_index=True, max_length=100)),
                ('hometown_state', models.CharField(db_index=True, max_length=100)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='colleges.college')),
            ],
        ),
    ]
